version: '3.7'
services:
    php-apache:
        restart: always
        image: webdev.loc
        container_name: php-apache
        ports:
            - 80:80
        depends_on:
            - db
        build:
            context: .docker/
            dockerfile: Dockerfile
        volumes:
            - ./app:/app
            - ./logs:/var/log/apache2
            - ./.docker/vhost.conf:/etc/apache2/sites-available/000-default.conf
        links:
            - db
    db:
        image: mysql:5.7
        container_name: mysql-db
        command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp=1
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./db:/var/lib/mysql
    adminer:
        image: adminer
        container_name: adminer
        restart: always
        depends_on:
            - db
        ports:
            - 8080:8080

